-- CreateTable
CREATE TABLE "appcompany"."JobApplication" (
    "id" TEXT NOT NULL,
    "positionId" TEXT,
    "positionTitle" TEXT NOT NULL,
    "namaLengkap" TEXT NOT NULL,
    "alamatKTP" TEXT NOT NULL,
    "alamatDomisili" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "tempatLahir" TEXT NOT NULL,
    "tanggalLahir" TEXT NOT NULL,
    "usia" TEXT NOT NULL,
    "anakKe" TEXT NOT NULL DEFAULT '',
    "dariSaudara" TEXT NOT NULL DEFAULT '',
    "nik" TEXT NOT NULL,
    "agama" TEXT NOT NULL,
    "golDarah" TEXT NOT NULL,
    "jenisKelamin" TEXT NOT NULL,
    "noTelp" TEXT NOT NULL,
    "kondisiMata" TEXT NOT NULL,
    "tinggiBadan" TEXT NOT NULL,
    "beratBadan" TEXT NOT NULL,
    "pendidikan" TEXT NOT NULL,
    "lulusTahun" TEXT NOT NULL,
    "statusNikah" TEXT NOT NULL,
    "bersediaShift" TEXT NOT NULL,
    "puyaTindikTato" TEXT NOT NULL,
    "perokok" TEXT NOT NULL,
    "riwayatPenyakit" TEXT NOT NULL DEFAULT '',
    "pengalamanKerja" JSONB NOT NULL DEFAULT '[]',
    "seminarKursus" JSONB NOT NULL DEFAULT '[]',
    "organisasi" JSONB NOT NULL DEFAULT '[]',
    "cvFileName" TEXT,
    "fotoFileName" TEXT,
    "cvData" BYTEA,
    "fotoData" BYTEA,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "JobApplication_pkey" PRIMARY KEY ("id")
);
